// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a07f058b-24b4-4c04-bd0b-dd6a67fa3af4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5BFoT0YNC",
    "aws_user_pools_web_client_id": "4d949dt29m58fujrl98ku08t0f",
    "aws_mobile_analytics_app_id": "f32cc6783c4142708843ecd69d03c66a",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "chatnoir-20181211090852-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://chatnoir-20181211090852-hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
